// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmx3V-d8APlO6CbLsMQ_Qrzg8noNuiXO0',
    appId: '1:688641494608:web:23e13d61de9af570bacb55',
    messagingSenderId: '688641494608',
    projectId: 'paybaygo-crm-f16f6',
    authDomain: 'paybaygo-crm-f16f6.firebaseapp.com',
    storageBucket: 'paybaygo-crm-f16f6.firebasestorage.app',
    measurementId: 'G-P7Z5CEQ32V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM4WbaDHv8t2y10sX_563UibRoBmRYudE',
    appId: '1:688641494608:ios:5b092c89149d9072bacb55',
    messagingSenderId: '688641494608',
    projectId: 'paybaygo-crm-f16f6',
    storageBucket: 'paybaygo-crm-f16f6.firebasestorage.app',
    iosBundleId: 'com.example.paybaygoCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmx3V-d8APlO6CbLsMQ_Qrzg8noNuiXO0',
    appId: '1:688641494608:web:85ab294ec4ad7beebacb55',
    messagingSenderId: '688641494608',
    projectId: 'paybaygo-crm-f16f6',
    authDomain: 'paybaygo-crm-f16f6.firebaseapp.com',
    storageBucket: 'paybaygo-crm-f16f6.firebasestorage.app',
    measurementId: 'G-JB2LEFPJ99',
  );
}
